### ISSUE TITLE
fix version output

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/atlassian-downloader#11]
fix version output

**Comment by kasthack** [comment]
Works fine for me

**Comment by kasthack** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/1292818/104814515-703a5180-5820-11eb-8816-69cf13e401c4.png)

**Comment by stamepicmorg** [comment]
a want to custom version output.

**Comment by stamepicmorg** [comment]
resolved at https://github.com/EpicMorg/atlassian-downloader/pull/15/commits/0b95530eed9a961fac304b1d4a148f6fe3b52169
![image](https://user-images.githubusercontent.com/1307229/105097175-39329d00-5ab9-11eb-9726-9e450c1bbddf.png)
