### ISSUE TITLE
add support of sourcetree

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/atlassian-downloader#9]
add support of sourcetree.

* https://www.sourcetreeapp.com/download
* https://www.sourcetreeapp.com/download-archives

download links splitted from atlassian site and jsons, they are hardcoded in to html page. 💩

**Comment by kasthack** [comment]
Nah

**Comment by stamepicmorg** [comment]
workround:  we will be add support of custom json feeds of `SourceTree` from `EpicMorg/atlassian-json` repo.
